name: Infracost Tagging Policy

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  infracost:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Infracost
        uses: infracost/actions/setup@v3
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Run cost breakdown
        run: infracost breakdown --path=. --format=json --out-file=infracost.json

      - name: Check tagging policy
        run: infracost policy --path=infracost.json --policy-path=./policies --format=json --out-file=policy.json

      - name: Post comment to PR
        uses: infracost/actions/comment@v3
        with:
          path: policy.json
